name: publish distributions
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

jobs:
  build-and-publish:
    name: Build and publish Python distro to (Test)PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pep517 and twine
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pep517 --user
        python -m pip install twine
    - name: Build a binary wheel and a source tarball
      run: |
        python -m pep517.build --source --binary --out-dir dist/ .
    - name: Check information
      run: |
        echo "${{ github.event.sender.login }}"
        echo $(git log -1 --pretty=format:"%an")
    - name: Verify untagged commits have dev versions
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: |
        printenv
        latest_tag=$(git describe --tags)
        echo "latest_tag: ${latest_tag}"
        latest_tag_revlist_SHA=$(git rev-list -n 1 ${latest_tag})
        echo "latest_tag_revlist_SHA: ${latest_tag_revlist_SHA}"
        echo "master_SHA: ${master_SHA}"
        echo "latest_tag_revlist_SHA: ${latest_tag_revlist_SHA}"
        wheel_name=$(find dist/ -iname "*.whl" -printf "%f\n")
        if [[ "${latest_tag_revlist_SHA}" != "${master_SHA}" ]]; then # don't check master push events from tags
          if [[ "${wheel_name}" == *"maxborn-0.1.dev"* || "${wheel_name}" != *"dev"* ]]; then
            echo "pep517.build incorrectly named built distribution: ${wheel_name}"
            echo "pep517 is lacking the history and tags required to determine version number"
            echo "intentionally erroring with 'return 1' now"
            return 1
          fi
        fi
        echo "pep517.build named built distribution: ${wheel_name}"
    - name: Verify tagged commits don't have dev versions
      if: startsWith(github.ref, 'refs/tags')
      run: |
        printenv
        wheel_name=$(find dist/ -iname "*.whl" -printf "%f\n")
        if [[ "${wheel_name}" == *"dev"* ]]; then
          echo "pep517.build incorrectly named built distribution: ${wheel_name}"
          echo "this is incorrrectly being treated as a dev release"
          echo "intentionally erroring with 'return 1' now"
          return 1
        fi
        echo "pep517.build named built distribution: ${wheel_name}"
    - name: Verify the distribution
      run: twine check dist/*
    - name: Publish distribution 📦 to Test PyPI
      # every PR will trigger a push event on master, so check the push event is actually coming from master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'matthewfeickert/throw-it-away-now'
      run: |
        echo "Publishing distribution to TestPyPI"
    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'matthewfeickert/throw-it-away-now'
      run: |
        echo "Publishing distribution to PyPI"
